const swaggerAutogen = require("swagger-autogen")();

const path = require("path");
const fs = require("fs");
const folderPath = path.join(__dirname, "../json");
const files = fs.readdirSync(folderPath);
const latestIndex = files
  .filter((file) => file.startsWith("swagger"))
  .map((file) => parseInt(file.replace("swagger", "").replace(".json", ""), 10))
  .reduce((max, current) => (current > max ? current : max), 0);

const doc = {
  info: {
    title: "TixPro API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
};

const outputFile = path.join(folderPath, `swagger${latestIndex + 1}.json`);
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc);
