const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    title: "TixPro API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: "http",
  securityDefinitions: {
    JWT: {
      type: "apiKey",
      description: "Type into the textbox: Bearer {your JWT token}.",
      name: "access_token",
      in: "header",
    },
  },
  security: [{ JWT: [] }],
};

const outputFile = "../json/swagger.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc);
